### ISSUE TITLE
Error string got int

### ISSUE THREAD

**Issue by fadjar340** [deric/es-dedupe#1]
Hi...

I have this error
```
Traceback (most recent call last):
  File "dedupe.py", line 420, in <module>
    run(args)
  File "dedupe.py", line 56, in run
    removed = check_docs(args.log_agg, args)
  File "dedupe.py", line 227, in check_docs
    deleted += msearch(buf.getvalue(), args, stats, i)
  File "dedupe.py", line 280, in msearch
    log_done(to_log, remain['_source'][args.field], remain['_index'], remain['_type'], remain['_id'])
  File "dedupe.py", line 161, in log_done
    buf.write(doc)
TypeError: string argument expected, got 'int'
```
Is there anything wrong in my command?

Regards,
Fadjar Tandabawana

**Comment by deric** [comment]
@fadjar340 Sorry, it's still quite early version. Try latest version from master branch.

> Is there anything wrong in my command?

I don't know which arguments did you use, but it looks like the unique field is `int` type.

**Comment by deric** [comment]
Please reopen if the problem persists.
