### ISSUE TITLE
Unauthorized esdedupe

### ISSUE THREAD

**Issue by dipenpatel235** [deric/es-dedupe#11]
i try below command and get error unauthorized.

```
docker run --rm deric/es-dedupe:latest esdedupe -H htttps://elastic_hostname -P 443 -i index_name \
-f md5 --user elastic_user --password "elastic_password"
```

**Comment by deric** [comment]
Try using the latest version:

```
docker run --rm deric/es-dedupe:v2.0.0 esdedupe -H elastic_hostname --noop
```
if you're using SSL, please use the `--ssl` flag:
```
docker run --rm deric/es-dedupe:v2.0.0 esdedupe -H elastic_hostname -P 443 --ssl -i index_name \
-f md5 --user elastic_user --password "elastic_password"
```

**Comment by dipenpatel235** [comment]
@deric it's the same issue..
after that i have try using below command so using that authentication done successfully but getting other error now
```
docker run -it --rm deric/es-dedupe:latest esdedupe -H http://myuser:mypassword@172.31.11.11 -P 9200 -i "myindex" -f source_ip,feed_provider
```
so its giving below  error and my given key name is correct
```
2021-10-01T12:46:41  [140129338693440] INFO  esdedupe Building documents mapping on index: myindex, batch size: 1000
Traceback (most recent call last):
  File "/usr/local/bin/esdedupe", line 11, in <module>
    load_entry_point('esdedupe==2.0.0', 'console_scripts', 'esdedupe')()
  File "/usr/local/lib/python3.7/dist-packages/esdedupe-2.0.0-py3.7.egg/esdedupe/cmd.py", line 67, in main
    lastcmd = ''
  File "/usr/local/lib/python3.7/dist-packages/esdedupe-2.0.0-py3.7.egg/esdedupe/esdedupe.py", line 109, in run
  File "/usr/local/lib/python3.7/dist-packages/esdedupe-2.0.0-py3.7.egg/esdedupe/esdedupe.py", line 169, in process_index
  File "/usr/local/lib/python3.7/dist-packages/esdedupe-2.0.0-py3.7.egg/esdedupe/esdedupe.py", line 188, in scan_and_remove
  File "/usr/local/lib/python3.7/dist-packages/esdedupe-2.0.0-py3.7.egg/esdedupe/esdedupe.py", line 178, in scan
  File "/usr/local/lib/python3.7/dist-packages/esdedupe-2.0.0-py3.7.egg/esdedupe/esdedupe.py", line 36, in build_index
KeyError: 'source_ip'
```

**Comment by deric** [comment]
That looks like different error than `Unauthorized` to me. 

`source_ip` field is probably not included in all documents. Try running the command with higher verbosity:
```
docker run -it --rm deric/es-dedupe:latest esdedupe -H http://myuser:mypassword@172.31.11.11 -P 9200 -i "myindex" -f source_ip,feed_provider --level DEBUG --es-level DEBUG
```

**Comment by dipenpatel235** [comment]
Yes it's possible it's not in all all documents.
.

**Comment by deric** [comment]
Then you can't use it as part of an unique key. I'll try to throw a better error message.

**Comment by dipenpatel235** [comment]
Ok... So is there any other way to delete ?
Because I needed this things .

**Comment by dipenpatel235** [comment]
@deric if the key field does not exist that I have fixed using the below method.
modified `esdedupe.py` line no 36 to below code. you can add this code block into your code and push it.
```
                try:
                    combined_key += str(hit['_source'][field])
                except Exception as e:
                    pass
```

**Comment by deric** [comment]
@dipenpatel235 That's not really a fix, rather a dirty-bomb which might lead to deleting all data from an index, if incorrect field name is used.

**Comment by dipenpatel235** [comment]
Yes right...
But something you can put restrictions on that if we can find better way..
But as of now I have did that for my custom solution.

**Comment by adhaamehab** [comment]
I had the same issue when passing `--user` and `--password`, the workaround is to pass the host as
`https://user:password@host:port` and pass `--ssl`
